export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'A futuristic cityscape with flying cars and neon lights.',
  'A serene beach at sunset with palm trees and gentle waves.',
  'A mystical forest with towering trees and magical creatures.',
  'An underwater world with colorful coral reefs and exotic fish.',
  'A cozy cabin nestled in the snowy mountains.',
  'A bustling marketplace filled with vendors and vibrant colors.',
  'An enchanted castle on a hill surrounded by lush gardens.',
  'A whimsical garden with talking animals and blooming flowers.',
  'A sci-fi spaceship traveling through outer space.',
  'A steampunk-inspired city with intricate clockwork machinery.',
  'A tranquil countryside landscape with rolling hills and grazing livestock.',
  'A magical waterfall with sparkling water and rainbow mist.',
  'A futuristic robot with sleek metallic features and glowing eyes.',
  'A surreal dreamscape with floating islands and surreal creatures.',
  'A futuristic city with advanced technology and holographic displays.',
  'A haunted mansion with crumbling walls and eerie atmosphere.',
  'A fantastical jungle with exotic plants and hidden treasures.',
  'A futuristic dystopian city with towering skyscrapers and polluted skies.',
  'A peaceful village with thatched-roof cottages and a flowing river.',
  'A mythical creature like a dragon, phoenix, or unicorn in a majestic pose.',
  'A surreal desert landscape with sand dunes and a colorful sky.',
  'A magical library filled with ancient books and mystical artifacts.',
  'A futuristic sports arena with high-tech equipment and cheering crowds.',
  'A fairytale castle in the clouds with floating islands.',
  'A vibrant street art mural depicting a cultural celebration.',
  'A serene mountain lake reflecting the surrounding peaks.',
  'A futuristic laboratory with scientists conducting experiments.',
  'A fantastical underwater kingdom with mermaids and underwater castles.',
  'A charming village market with stalls selling fresh produce and handmade crafts.',
  'A whimsical carousel with brightly painted animals and twinkling lights.',
  'A space colony on another planet with futuristic architecture.',
  'A serene zen garden with carefully arranged rocks and lush greenery.',
  'A medieval castle perched on a cliff overlooking the sea.',
  'A lush rainforest with towering trees and a hidden waterfall.',
  'A futuristic train station with sleek bullet trains arriving and departing.',
  'A vibrant city street during a festive parade.',
  'A serene countryside landscape with a winding river and blooming flowers.',
  'A mythical underwater creature like a sea serpent or kraken in its natural habitat.',
  'A surreal underwater cave with bioluminescent plants and creatures.',
  'A futuristic factory with advanced machinery and robotic workers.',
  'A magical floating island with waterfalls cascading into the sky.',
  'A bustling futuristic city with flying vehicles and holographic advertisements.',
  'A tranquil temple atop a mist-covered mountain.',
  'A post-apocalyptic wasteland with crumbling buildings and overgrown vegetation.',
  'A whimsical treehouse nestled in a giant ancient tree.',
  'A picturesque vineyard with rows of grapevines and a quaint farmhouse.',
  'A futuristic amusement park with gravity-defying rides and virtual reality experiences.',
  'A hidden underground cave system with glowing crystals and stalactites.',
  'A steampunk-inspired airship sailing through the clouds.',
  'A peaceful lakeside cabin surrounded by autumn foliage.',
  ];